/**
 * Part of the With FBraun project template.
 * Author: František Braun <frantisek.braun95@gmail.com>
 * Freely available as a template for building custom applications.
 */

// Boards: /categories (every category), /categories/:slug (one category's
// posts, endlessly scrolling, with the form to add one), /categories/new,
// /my-posts (your own posts - find them again, raise their value),
// /my-payments (what you paid and for which post), /receipts (the documents) and
// /moderation (this application's administrators). CategoriesList is
// exported for applications that want it on other pages too (the home page
// does).
import type { ModuleDefinition } from '../types'
import CategoriesPage from './CategoriesPage'
import CategoryPage from './CategoryPage'
import ModerationPage from './ModerationPage'
import MyPostsPage from './MyPostsPage'
import NewCategoryPage from './NewCategoryPage'
import PaymentsPage from './PaymentsPage'
import ReceiptsPage from './ReceiptsPage'

export { default as CategoriesList } from './CategoriesList'

const boardsModule: ModuleDefinition = {
  key: 'boards',
  routes: [
    { path: '/categories', element: <CategoriesPage /> },
    // Declared before :slug for readability; react-router ranks the static
    // segment higher either way (and the backend never issues "new" as a slug).
    { path: '/categories/new', element: <NewCategoryPage /> },
    { path: '/categories/:slug', element: <CategoryPage /> },
    { path: '/my-posts', element: <MyPostsPage /> },
    { path: '/my-payments', element: <PaymentsPage /> },
    { path: '/receipts', element: <ReceiptsPage /> },
    { path: '/moderation', element: <ModerationPage /> },
  ],
  nav: [{ to: '/categories', labelKey: 'boards:nav.categories' }],
  locales: {
    cs: {
      nav: { categories: 'Kategorie' },
      common: { loading: 'Načítání…', loadMore: 'Načíst další', retry: 'Zkusit znovu' },
      list: {
        title: 'Kategorie',
        create: 'Nová kategorie',
        loginToCreate: 'Přihlaste se a založte kategorii',
        moderation: 'Moderace',
        myPosts: 'Moje příspěvky',
        empty: 'Zatím tu není žádná kategorie.',
        error: 'Kategorie se nepodařilo načíst.',
        posts_one: '{{count}} příspěvek',
        posts_few: '{{count}} příspěvky',
        posts_many: '{{count}} příspěvku',
        posts_other: '{{count}} příspěvků',
      },
      category: {
        back: 'Všechny kategorie',
        notFound: 'Kategorie nebyla nalezena.',
        loadError: 'Kategorii se nepodařilo načíst.',
        loginToPost: 'Přihlaste se, abyste mohli přidat příspěvek a vyjádřit souznění.',
        empty: 'Zatím tu není žádný příspěvek. Buďte první.',
        error: 'Příspěvky se nepodařilo načíst.',
      },
      post: {
        value: 'Hodnota',
        resonances_one: '{{count}} souznění',
        resonances_few: '{{count}} souznění',
        resonances_many: '{{count}} souznění',
        resonances_other: '{{count}} souznění',
        resonate: 'Souzním',
        resonated: 'Souznění vyjádřeno',
        loginToResonate: 'Přihlaste se, abyste mohli vyjádřit souznění',
        resonateError: 'Souznění se nepodařilo uložit.',
        yours: 'Váš příspěvek',
        paidByYou: 'zaplatili jste {{amount}}',
      },
      boost: {
        open: 'Zvýšit hodnotu',
        close: 'Zavřít',
        heading: 'Zvýšit hodnotu příspěvku',
        published: 'Příspěvek „{{title}}“ byl zveřejněn. Chcete hned zvýšit jeho hodnotu?',
        explain: 'Zaplacená částka se přičte k hodnotě příspěvku: 1 USD = {{points}} bodů. Platby se sčítají a hodnotu příspěvku postupně snižuje stáří.',
        amount: 'Částka v USD ({{min}}–{{max}})',
        points: '+{{points}} bodů',
        invalid: 'Zadejte celé číslo od {{min}} do {{max}} USD.',
        noRefund: 'Zaplacená částka se nevrací, pokud je příspěvek později zablokován pro porušení pravidel. Viz <rules>pravidla a podmínky</rules>.',
        pay: 'Objednat a zaplatit {{amount}}',
        payDisabled: 'Objednat a zaplatit',
      },
      myPosts: {
        title: 'Moje příspěvky',
        explain: 'Příspěvky jsou na nástěnkách anonymní. Tady najdete své, vidíte jejich hodnotu a můžete ji zvýšit.',
        loginRequired: 'Pro zobrazení svých příspěvků se přihlaste.',
        payments: 'Přehled plateb',
        receipts: 'Doklady o platbách',
        empty: 'Zatím jste nic nezveřejnili.',
        error: 'Příspěvky se nepodařilo načíst.',
        paid: 'zaplaceno {{amount}}',
        reason: 'Důvod odstranění',
        status: { published: 'Zveřejněný', blocked: 'Zablokovaný', removed: 'Odstraněný', hidden: 'Skrytý' },
        hiddenNote:
          'Kategorii zablokoval administrátor, a proto příspěvek teď nikdo nevidí. Nic se nesmazalo: pokud kategorii obnoví, příspěvek se vrátí i se zaplacenou částkou.',
      },
      receipts: {
        title: 'Moje doklady',
        explain: 'Doklady o vašich platbách. Potvrzení smlouvy s dokladem vám po každé platbě přijde i e-mailem.',
        loginRequired: 'Pro zobrazení dokladů se přihlaste.',
        empty: 'Zatím jste nic neplatili.',
        error: 'Doklady se nepodařilo načíst.',
        documentError: 'Doklad se nepodařilo načíst.',
        show: 'Zobrazit',
        emailed: 'Odesláno e-mailem',
        notEmailed: 'E-mail se nepodařilo odeslat – doklad najdete zde.',
        frameTitle: 'Doklad {{number}}',
        payments: 'Přehled plateb',
      },
      payments: {
        title: 'Moje platby',
        explain: 'Všechny vaše platby za zvýšení hodnoty příspěvků, i ty, které se nedokončily. Ke každé zaplacené platbě patří doklad.',
        receipts: 'Doklady',
        loginRequired: 'Pro zobrazení plateb se přihlaste.',
        empty: 'Zatím jste nic neplatili.',
        error: 'Platby se nepodařilo načíst.',
        total: 'Celkem zaplaceno',
        count_one: 'v {{count}} platbě',
        count_few: 've {{count}} platbách',
        count_many: 've {{count}} platbách',
        count_other: 've {{count}} platbách',
        status: { pending: 'Čeká na potvrzení', paid: 'Zaplaceno', failed: 'Nezdařilo se', expired: 'Nedokončeno' },
        points: '+{{points}} bodů',
        pendingNote: 'Platba zatím nebyla potvrzena. Pokud jste ji dokončili, potvrzení může chvíli trvat; nedokončená platba se do celkové částky nepočítá.',
        document: 'Doklad {{number}}',
        postState: {
          gone: 'příspěvek nenalezen',
          blocked: 'Příspěvek byl zablokován, zaplacená částka se nevrací.',
          removed: 'Příspěvek byl odstraněn, zaplacená částka se nevrací.',
          hidden: 'Příspěvek je skrytý, protože administrátor zablokoval jeho kategorii. Zaplacená částka mu zůstává.',
        },
        noRefund: 'Za příspěvek zablokovaný pro porušení pravidel se zaplacená částka nevrací. Viz <rules>pravidla a podmínky</rules>.',
      },

      form: {
        heading: 'Přidat příspěvek',
        title: 'Nadpis',
        body: 'Text',
        emoji: 'Emotikony',
        counter: '{{current}} / {{max}}',
        publish: 'Zveřejnit',
        checking: 'Kontrola…',
        publishing: 'Zveřejňování…',
        published: 'Příspěvek byl zveřejněn. Řadí se podle své hodnoty, takže se objeví mezi ostatními podle ní.',
        invalid: 'Zkontrolujte nadpis a text – nesmí být prázdné ani příliš dlouhé.',
        error: 'Příspěvek se nepodařilo zveřejnit.',
        accountBlocked: 'Váš účet je zablokován, příspěvky nelze přidávat.',
        rulesNotice: 'Zveřejněním souhlasíte s <rules>pravidly a podmínkami</rules>.',
      },
      newCategory: {
        title: 'Nová kategorie',
        name: 'Název',
        nameHint: 'Adresa kategorie se vytvoří z názvu.',
        description: 'Krátký popis',
        descriptionHint: 'Z názvu a popisu se vytvoří pravidla, podle kterých se posuzuje, zda příspěvky do kategorie patří.',
        create: 'Založit kategorii',
        creating: 'Zakládání…',
        loginRequired: 'Pro založení kategorie se přihlaste.',
        invalid: 'Zkontrolujte název a popis – nesmí být prázdné ani příliš dlouhé.',
        error: 'Kategorii se nepodařilo založit.',
        accountBlocked: 'Váš účet je zablokován, kategorie nelze zakládat.',
        rulesNotice: 'Zveřejněním souhlasíte s <rules>pravidly a podmínkami</rules>.',
      },
      blocked: {
        title: 'Váš účet je zablokován.',
        reason: {
          repeated_violations:
            'Měli jste příliš mnoho příspěvků označených jako závadné. Příspěvky ani kategorie nelze přidávat a souznění vyjadřovat.',
          unknown: 'Příspěvky ani kategorie nelze přidávat a souznění vyjadřovat.',
        },
        help: 'Pokud si myslíte, že jde o omyl, <contact>napište nám</contact>. Podrobnosti najdete v <rules>pravidlech a podmínkách</rules>.',
      },
      moderation: {
        warn: {
          post: 'U příspěvku jsme našli možný problém. Zvažte jeho úpravu.',
          category: 'U kategorie jsme našli možný problém. Zvažte její úpravu.',
        },
        risk: {
          post: 'Příspěvek je potenciálně závadný nebo mimo téma. Při podrobnějším posouzení může být zablokován a smazán bez náhrady zaplacené částky.',
          category: 'Obsah je potenciálně závadný. Při podrobnějším posouzení může být kategorie zablokována.',
        },
        blocked: {
          post: 'Příspěvek nevyhovuje pravidlům nebo neodpovídá kategorii, a proto ho nelze zveřejnit.',
          category: 'Kategorie nevyhovuje pravidlům a zveřejnění není povoleno.',
        },
        violationScore: 'Porušení pravidel',
        topicScore: 'Neshoda s tématem kategorie',
        levelName: { ok: 'v pořádku', warn: 'doporučena úprava', risk: 'potenciální riziko', blocked: 'nepovoleno' },
        why: 'Proč:',
        foundIn: 'nalezeno',
        categoryIsAbout: 'kategorie je o (ve vašem textu chybí)',
        publishAnyway: 'Přesto zveřejnit',
        createAnyway: 'Přesto založit',
        edit: 'Upravit',
        seeRules: 'Co je dovoleno, určují <rules>pravidla a podmínky</rules>.',
        finding: {
          profanity: 'Obsahuje vulgární výrazy.',
          insult: 'Obsahuje urážky.',
          hate: 'Obsahuje nenávistné nebo diskriminační výrazy.',
          threat: 'Obsahuje výhrůžky nebo vyzývá k násilí.',
          spam_links: 'Obsahuje odkazy typické pro spam.',
          spam_phrases: 'Obsahuje fráze typické pro spam nebo podvody.',
          personal_data: 'Obsahuje osobní údaje (e-mail, telefon).',
          shouting: 'Je psán křikem (velká písmena, řetězce vykřičníků).',
          repetition: 'Opakuje stejná slova nebo znaky.',
          gibberish: 'Obsahuje nesrozumitelně dlouhé řetězce znaků.',
          spam: 'Vypadá jako spam nebo reklama.',
          sexual_content: 'Obsahuje nevhodný sexuální obsah.',
          self_harm: 'Vybízí k sebepoškozování.',
          illegal_content: 'Obsahuje nelegální obsah.',
          misinformation: 'Obsahuje záměrné dezinformace.',
          off_topic: 'Neodpovídá tématu kategorie.',
          ai_other: 'Další důvod byl nalezen při automatickém posouzení.',
          unknown: 'Další důvod byl nalezen při posouzení.',
        },
      },
      notification: {
        postBlocked: 'Váš příspěvek „{{title}}“ byl odstraněn pro porušení pravidel. Důvod: {{reason}}',
        accountBlocked:
          'Váš účet byl zablokován pro opakované porušení pravidel. Nelze přidávat příspěvky ani kategorie a vyjadřovat souznění.',
        postRestored: 'Váš příspěvek „{{title}}“ byl obnoven a je zase zveřejněný. Omlouváme se za potíže.',
        categoryBlocked: 'Vaše kategorie „{{title}}“ byla zablokována pro porušení pravidel a už není veřejná. Důvod: {{reason}}',
        categoryRestored: 'Vaše kategorie „{{title}}“ byla obnovena a je zase veřejná.',
      },
      admin: {
        title: 'Moderace',
        loginRequired: 'Pro přístup k moderaci se přihlaste.',
        forbidden: 'K moderaci nemáte oprávnění.',
        error: 'Operace se nezdařila.',
        cancel: 'Zrušit',
        tabs: { posts: 'Příspěvky', categories: 'Kategorie', rules: 'Pravidla kategorií', accounts: 'Zablokované účty' },
        status: { published: 'Zveřejněné', blocked: 'Zablokované', removed: 'Odstraněné', all: 'Všechny' },
        reason: {
          account_blocked: 'odstraněno se zablokováním účtu autora',
          repeated_violations: 'opakovaná porušení pravidel',
        },
        posts: {
          search: 'Hledat v textu',
          category: 'Kategorie (adresa)',
          status: 'Stav',
          minScore: 'Skóre od (%)',
          sort: 'Řazení',
          sortNew: 'Nejnovější',
          sortScore: 'Nejvyšší skóre',
          find: 'Najít',
          empty: 'Nic nenalezeno.',
          scores: 'porušení {{violation}} %, téma {{topic}} %',
          reason: 'Důvod blokace',
          author: 'Autor',
          authorBlocked: 'účet autora je zablokován',
          categoryBlocked: 'Kategorie je zablokována – příspěvek veřejně není vidět.',
          block: 'Zablokovat…',
          editRules: 'Pravidla kategorie',
          blocked: 'Příspěvek byl zablokován a autor upozorněn.',
          accountBlocked: 'Účet autora byl zablokován.',
          reasonLabel: 'Důvod (uvidí ho autor jako oznámení)',
          reasonHint: 'Příspěvek bude odstraněn bez náhrady zaplacené částky.',
          confirmBlock: 'Zablokovat příspěvek',
          restore: 'Obnovit',
          confirmRestore: 'Obnovit příspěvek? Zveřejní se znovu i se zaplacenou částkou, přestane se počítat jako závadný a autor o tom dostane oznámení.',
          restoredDone: 'Příspěvek byl obnoven a autor upozorněn.',
          restoreAuthorBlocked: 'Účet autora je zablokován. Nejdřív ho odblokujte (záložka Zablokované účty), pak příspěvek obnovte.',
        },
        categories: {
          explain:
            'Všechny kategorie, i zablokované (veřejný seznam je vynechává). Zablokovaná kategorie zmizí pro návštěvníky i se všemi příspěvky, nelze do ní psát, souznít ani platit. Nic se nemaže: po obnovení je všechno, jak bylo. Příspěvky ani jejich autoři se tím nepenalizují.',
          search: 'Hledat v názvu a adrese',
          empty: 'Nic nenalezeno.',
          created: 'založeno {{date}}, skóre při založení {{score}} %',
          creator: 'Zakladatel',
          block: 'Zablokovat…',
          restore: 'Obnovit',
          reasonLabel: 'Důvod (uvidí ho zakladatel kategorie jako oznámení)',
          reasonHint: 'Kategorie i s příspěvky zmizí ze všech seznamů; nic se nemaže a po obnovení se vrátí.',
          confirmBlock: 'Zablokovat kategorii',
          confirmRestore: 'Obnovit kategorii? Vrátí se i se všemi příspěvky a zakladatel o tom dostane oznámení.',
          blockedDone: 'Kategorie byla zablokována a zakladatel upozorněn.',
          restoredDone: 'Kategorie byla obnovena a zakladatel upozorněn.',
        },
        rules: {
          category: 'Kategorie (adresa)',
          load: 'Načíst',
          pick: 'Zadejte adresu kategorie.',
          source: 'Zdroj pravidel: {{source}}',
          none: 'žádná pravidla',
          sources: { algorithm: 'algoritmus', ai: 'model AI', admin: 'administrátor' },
          explain:
            'Příspěvky se porovnávají s těmito klíčovými slovy. Čím vyšší váha, tím víc slovo o kategorii vypovídá. Prázdný seznam vypne kontrolu tématu.',
          empty: 'Kategorie nemá žádná klíčová slova – kontrola tématu je vypnutá.',
          term: 'Klíčové slovo',
          weight: 'Váha',
          remove: 'Odebrat',
          add: '+ Přidat klíčové slovo',
          notes: 'Poznámky',
          save: 'Uložit pravidla',
          rebuild: 'Vytvořit znovu z názvu a popisu',
          confirmRebuild: 'Současná pravidla (včetně vašich úprav) se zahodí a vytvoří se znovu z názvu a popisu kategorie. Pokračovat?',
          saved: 'Pravidla byla uložena.',
          rebuilt: 'Pravidla byla vytvořena znovu.',
          invalid: 'Zkontrolujte pravidla – klíčová slova nesmí být prázdná a váha musí být mezi 0,1 a 10.',
        },
        accounts: {
          explain: 'Účty zablokované pro opakovaná porušení pravidel. Odblokováním účet začne s čistým štítem; odstraněné příspěvky se samy nevrátí, ale můžete je obnovit na záložce Příspěvky (stav Odstraněné).',
          empty: 'Žádné zablokované účty.',
          unblock: 'Odblokovat',
          confirmUnblock: 'Odblokovat účet? Dřívější porušení se přestanou počítat, odstraněné příspěvky se ale samy nevrátí – obnovíte je jednotlivě.',
        },
      },
    },
    en: {
      nav: { categories: 'Categories' },
      common: { loading: 'Loading…', loadMore: 'Load more', retry: 'Try again' },
      list: {
        title: 'Categories',
        create: 'New category',
        loginToCreate: 'Sign in to create a category',
        moderation: 'Moderation',
        myPosts: 'My posts',
        empty: 'There are no categories yet.',
        error: 'Could not load the categories.',
        posts_one: '{{count}} post',
        posts_other: '{{count}} posts',
      },
      category: {
        back: 'All categories',
        notFound: 'Category not found.',
        loadError: 'Could not load the category.',
        loginToPost: 'Sign in to add a post and to resonate.',
        empty: 'No posts here yet. Be the first.',
        error: 'Could not load the posts.',
      },
      post: {
        value: 'Value',
        resonances_one: '{{count}} resonance',
        resonances_other: '{{count}} resonances',
        resonate: 'Resonate',
        resonated: 'You resonated',
        loginToResonate: 'Sign in to resonate',
        resonateError: 'Could not save your resonance.',
        yours: 'Your post',
        paidByYou: 'you paid {{amount}}',
      },
      boost: {
        open: 'Raise value',
        close: 'Close',
        heading: 'Raise the value of this post',
        published: 'Your post “{{title}}” was published. Want to raise its value now?',
        explain: 'The amount you pay is added to the post’s value: 1 USD = {{points}} points. Payments add up, and the post’s value is gradually reduced by its age.',
        amount: 'Amount in USD ({{min}}–{{max}})',
        points: '+{{points}} points',
        invalid: 'Enter a whole number from {{min}} to {{max}} USD.',
        noRefund: 'The amount paid is not refunded if the post is later blocked for breaking the rules. See the <rules>terms and rules</rules>.',
        pay: 'Order and pay {{amount}}',
        payDisabled: 'Order and pay',
      },
      myPosts: {
        title: 'My posts',
        explain: 'Posts are anonymous on the boards. Here you find your own, see what they are worth and can raise their value.',
        loginRequired: 'Sign in to see your posts.',
        payments: 'Payment overview',
        receipts: 'Payment receipts',
        empty: 'You have not published anything yet.',
        error: 'Could not load the posts.',
        paid: 'paid {{amount}}',
        reason: 'Reason for removal',
        status: { published: 'Published', blocked: 'Blocked', removed: 'Removed', hidden: 'Hidden' },
        hiddenNote:
          'An administrator blocked the category, so nobody can see this post right now. Nothing was deleted: if the category is restored, the post comes back with what was paid for it.',
      },
      receipts: {
        title: 'My receipts',
        explain: 'The documents for your payments. After each payment the contract confirmation with its document is also emailed to you.',
        loginRequired: 'Sign in to see your receipts.',
        empty: 'You have not paid for anything yet.',
        error: 'Could not load the receipts.',
        documentError: 'Could not load the document.',
        show: 'Show',
        emailed: 'Sent by email',
        notEmailed: 'The email could not be sent – you can read the document here.',
        frameTitle: 'Document {{number}}',
        payments: 'Payment overview',
      },
      payments: {
        title: 'My payments',
        explain: 'All your payments to raise the value of posts, including the ones that were not completed. Every completed payment has a document.',
        receipts: 'Documents',
        loginRequired: 'Sign in to see your payments.',
        empty: 'You have not paid for anything yet.',
        error: 'Could not load the payments.',
        total: 'Paid in total',
        count_one: 'in {{count}} payment',
        count_other: 'in {{count}} payments',
        status: { pending: 'Awaiting confirmation', paid: 'Paid', failed: 'Failed', expired: 'Not completed' },
        points: '+{{points}} points',
        pendingNote: 'The payment has not been confirmed yet. If you completed it, the confirmation may take a moment; a payment that was not completed does not count towards the total.',
        document: 'Document {{number}}',
        postState: {
          gone: 'post not found',
          blocked: 'The post was blocked; the amount paid is not refunded.',
          removed: 'The post was removed; the amount paid is not refunded.',
          hidden: 'The post is hidden because an administrator blocked its category. The amount paid stays with it.',
        },
        noRefund: 'The amount paid is not refunded for a post blocked for breaking the rules. See the <rules>terms and rules</rules>.',
      },

      form: {
        heading: 'Add a post',
        title: 'Title',
        body: 'Text',
        emoji: 'Emoji',
        counter: '{{current}} / {{max}}',
        publish: 'Publish',
        checking: 'Checking…',
        publishing: 'Publishing…',
        published: 'Your post was published. Posts are ordered by value, so it appears among the others accordingly.',
        invalid: 'Check the title and the text – they cannot be empty or too long.',
        error: 'Could not publish the post.',
        accountBlocked: 'Your account is blocked, so you cannot add posts.',
        rulesNotice: 'By publishing you agree to the <rules>terms and rules</rules>.',
      },
      newCategory: {
        title: 'New category',
        name: 'Name',
        nameHint: "The category's address is generated from its name.",
        description: 'Short description',
        descriptionHint: 'The name and description are turned into the rules that decide whether a post belongs in the category.',
        create: 'Create category',
        creating: 'Creating…',
        loginRequired: 'Sign in to create a category.',
        invalid: 'Check the name and the description – they cannot be empty or too long.',
        error: 'Could not create the category.',
        accountBlocked: 'Your account is blocked, so you cannot create categories.',
        rulesNotice: 'By publishing you agree to the <rules>terms and rules</rules>.',
      },
      blocked: {
        title: 'Your account is blocked.',
        reason: {
          repeated_violations:
            'Too many of your posts were marked as violating the rules. You cannot add posts or categories or resonate.',
          unknown: 'You cannot add posts or categories or resonate.',
        },
        help: 'If you think this is a mistake, <contact>write to us</contact>. You can read the details in the <rules>terms and rules</rules>.',
      },
      moderation: {
        warn: {
          post: 'We found a possible problem with your post. Consider editing it.',
          category: 'We found a possible problem with your category. Consider editing it.',
        },
        risk: {
          post: 'The post is potentially violating the rules or off-topic. After a closer review it may be blocked and deleted without a refund of what was paid for it.',
          category: 'The content is potentially violating. After a closer review the category may be blocked.',
        },
        blocked: {
          post: 'The post does not meet the rules or does not fit the category, so it cannot be published.',
          category: 'The category does not meet the rules and cannot be published.',
        },
        violationScore: 'Rule violation',
        topicScore: "Mismatch with the category's topic",
        levelName: { ok: 'fine', warn: 'edit recommended', risk: 'potential risk', blocked: 'not allowed' },
        why: 'Why:',
        foundIn: 'found',
        categoryIsAbout: 'the category is about (missing from your text)',
        publishAnyway: 'Publish anyway',
        createAnyway: 'Create anyway',
        edit: 'Edit',
        seeRules: 'What is allowed is set out in the <rules>terms and rules</rules>.',
        finding: {
          profanity: 'Contains vulgar expressions.',
          insult: 'Contains insults.',
          hate: 'Contains hateful or discriminatory expressions.',
          threat: 'Contains threats or incites violence.',
          spam_links: 'Contains links typical of spam.',
          spam_phrases: 'Contains phrases typical of spam or scams.',
          personal_data: 'Contains personal data (email, phone).',
          shouting: 'Is written in shouting (capitals, strings of exclamation marks).',
          repetition: 'Repeats the same words or characters.',
          gibberish: 'Contains unreadably long strings of characters.',
          spam: 'Looks like spam or advertising.',
          sexual_content: 'Contains inappropriate sexual content.',
          self_harm: 'Encourages self-harm.',
          illegal_content: 'Contains illegal content.',
          misinformation: 'Contains deliberate misinformation.',
          off_topic: 'Does not fit the category topic.',
          ai_other: 'Another reason was found by the automatic review.',
          unknown: 'Another reason was found in the review.',
        },
      },
      notification: {
        postBlocked: 'Your post "{{title}}" was removed for breaking the rules. Reason: {{reason}}',
        accountBlocked:
          'Your account was blocked for repeated rule violations. You can no longer add posts or categories or resonate.',
        postRestored: 'Your post "{{title}}" was restored and is published again. We are sorry for the trouble.',
        categoryBlocked: 'Your category "{{title}}" was blocked for breaking the rules and is no longer public. Reason: {{reason}}',
        categoryRestored: 'Your category "{{title}}" was restored and is public again.',
      },
      admin: {
        title: 'Moderation',
        loginRequired: 'Sign in to reach moderation.',
        forbidden: 'You are not allowed to moderate.',
        error: 'The operation failed.',
        cancel: 'Cancel',
        tabs: { posts: 'Posts', categories: 'Categories', rules: 'Category rules', accounts: 'Blocked accounts' },
        status: { published: 'Published', blocked: 'Blocked', removed: 'Removed', all: 'All' },
        reason: {
          account_blocked: 'removed when its author was blocked',
          repeated_violations: 'repeated rule violations',
        },
        posts: {
          search: 'Search the text',
          category: 'Category (address)',
          status: 'State',
          minScore: 'Score from (%)',
          sort: 'Order',
          sortNew: 'Newest',
          sortScore: 'Highest score',
          find: 'Find',
          empty: 'Nothing found.',
          scores: 'violation {{violation}} %, topic {{topic}} %',
          reason: 'Reason for blocking',
          author: 'Author',
          authorBlocked: "the author's account is blocked",
          categoryBlocked: "The category is blocked - the post can't be seen publicly.",
          block: 'Block…',
          editRules: "Category's rules",
          blocked: 'The post was blocked and its author notified.',
          accountBlocked: "The author's account was blocked.",
          reasonLabel: 'Reason (the author will see it as a notification)',
          reasonHint: 'The post is removed without a refund of what was paid for it.',
          confirmBlock: 'Block the post',
          restore: 'Restore',
          confirmRestore: 'Restore this post? It is published again with what was paid for it, stops counting as a violation, and its author is notified.',
          restoredDone: 'The post was restored and its author notified.',
          restoreAuthorBlocked: "The author's account is blocked. Unblock it first (the Blocked accounts tab), then restore the post.",
        },
        categories: {
          explain:
            "Every category, blocked ones included (the public list leaves them out). A blocked category disappears for visitors together with all its posts, and nothing can be posted, resonated with or paid for in it. Nothing is deleted: once it is restored, everything is as it was. This is no penalty for the posts or their authors.",
          search: 'Search the title and address',
          empty: 'Nothing found.',
          created: 'created {{date}}, score when created {{score}} %',
          creator: 'Creator',
          block: 'Block…',
          restore: 'Restore',
          reasonLabel: 'Reason (the category\'s creator will see it as a notification)',
          reasonHint: 'The category disappears from every list together with its posts; nothing is deleted, and it comes back when restored.',
          confirmBlock: 'Block the category',
          confirmRestore: 'Restore this category? It comes back with all its posts, and its creator is notified.',
          blockedDone: 'The category was blocked and its creator notified.',
          restoredDone: 'The category was restored and its creator notified.',
        },
        rules: {
          category: 'Category (address)',
          load: 'Load',
          pick: "Enter a category's address.",
          source: 'Rules from: {{source}}',
          none: 'no rules',
          sources: { algorithm: 'the algorithm', ai: 'the AI model', admin: 'an administrator' },
          explain:
            "Posts are compared with these keywords. The higher the weight, the more the word says about the category. An empty list switches the topic check off.",
          empty: 'The category has no keywords - the topic check is off.',
          term: 'Keyword',
          weight: 'Weight',
          remove: 'Remove',
          add: '+ Add a keyword',
          notes: 'Notes',
          save: 'Save rules',
          rebuild: 'Rebuild from the title and description',
          confirmRebuild: "The current rules (your edits included) will be thrown away and built again from the category's title and description. Continue?",
          saved: 'The rules were saved.',
          rebuilt: 'The rules were rebuilt.',
          invalid: 'Check the rules - keywords cannot be empty and a weight must be between 0.1 and 10.',
        },
        accounts: {
          explain: 'Accounts blocked for repeated rule violations. Unblocking gives an account a clean slate; removed posts do not come back by themselves, but you can restore them on the Posts tab (state Removed).',
          empty: 'No blocked accounts.',
          unblock: 'Unblock',
          confirmUnblock: 'Unblock this account? Earlier violations stop counting, but removed posts do not come back by themselves - you restore them one by one.',
        },
      },
    },
  },
}

export default boardsModule
