/**
 * Part of the With FBraun project template.
 * Author: František Braun <frantisek.braun95@gmail.com>
 * Freely available as a template for building custom applications.
 */

// Boards: /categories (every category), /categories/:slug (one category's
// posts, endlessly scrolling, with the form to add one), /categories/new,
// and /moderation (this application's administrators). CategoriesList is
// exported for applications that want it on other pages too (the home page
// does).
import type { ModuleDefinition } from '../types'
import CategoriesPage from './CategoriesPage'
import CategoryPage from './CategoryPage'
import ModerationPage from './ModerationPage'
import NewCategoryPage from './NewCategoryPage'

export { default as CategoriesList } from './CategoriesList'

const boardsModule: ModuleDefinition = {
  key: 'boards',
  routes: [
    { path: '/categories', element: <CategoriesPage /> },
    // Declared before :slug for readability; react-router ranks the static
    // segment higher either way (and the backend never issues "new" as a slug).
    { path: '/categories/new', element: <NewCategoryPage /> },
    { path: '/categories/:slug', element: <CategoryPage /> },
    { path: '/moderation', element: <ModerationPage /> },
  ],
  nav: [{ to: '/categories', labelKey: 'boards:nav.categories' }],
  locales: {
    cs: {
      nav: { categories: 'Kategorie' },
      common: { loading: 'Načítání…', loadMore: 'Načíst další', retry: 'Zkusit znovu' },
      list: {
        title: 'Kategorie',
        create: 'Nová kategorie',
        loginToCreate: 'Přihlaste se a založte kategorii',
        moderation: 'Moderace',
        empty: 'Zatím tu není žádná kategorie.',
        error: 'Kategorie se nepodařilo načíst.',
        posts_one: '{{count}} příspěvek',
        posts_few: '{{count}} příspěvky',
        posts_many: '{{count}} příspěvku',
        posts_other: '{{count}} příspěvků',
      },
      category: {
        back: 'Všechny kategorie',
        notFound: 'Kategorie nebyla nalezena.',
        loadError: 'Kategorii se nepodařilo načíst.',
        loginToPost: 'Přihlaste se, abyste mohli přidat příspěvek a vyjádřit souznění.',
        empty: 'Zatím tu není žádný příspěvek. Buďte první.',
        error: 'Příspěvky se nepodařilo načíst.',
      },
      post: {
        value: 'Hodnota',
        resonances_one: '{{count}} souznění',
        resonances_few: '{{count}} souznění',
        resonances_many: '{{count}} souznění',
        resonances_other: '{{count}} souznění',
        resonate: 'Souzním',
        resonated: 'Souznění vyjádřeno',
        loginToResonate: 'Přihlaste se, abyste mohli vyjádřit souznění',
        resonateError: 'Souznění se nepodařilo uložit.',
      },
      form: {
        heading: 'Přidat příspěvek',
        title: 'Nadpis',
        body: 'Text',
        emoji: 'Emotikony',
        counter: '{{current}} / {{max}}',
        publish: 'Zveřejnit',
        checking: 'Kontrola…',
        publishing: 'Zveřejňování…',
        published: 'Příspěvek byl zveřejněn. Řadí se podle své hodnoty, takže se objeví mezi ostatními podle ní.',
        invalid: 'Zkontrolujte nadpis a text – nesmí být prázdné ani příliš dlouhé.',
        error: 'Příspěvek se nepodařilo zveřejnit.',
        accountBlocked: 'Váš účet je zablokován, příspěvky nelze přidávat.',
        rulesNotice: 'Zveřejněním souhlasíte s <rules>pravidly a podmínkami</rules>.',
      },
      newCategory: {
        title: 'Nová kategorie',
        name: 'Název',
        nameHint: 'Adresa kategorie se vytvoří z názvu.',
        description: 'Krátký popis',
        descriptionHint: 'Z názvu a popisu se vytvoří pravidla, podle kterých se posuzuje, zda příspěvky do kategorie patří.',
        create: 'Založit kategorii',
        creating: 'Zakládání…',
        loginRequired: 'Pro založení kategorie se přihlaste.',
        invalid: 'Zkontrolujte název a popis – nesmí být prázdné ani příliš dlouhé.',
        error: 'Kategorii se nepodařilo založit.',
        accountBlocked: 'Váš účet je zablokován, kategorie nelze zakládat.',
        rulesNotice: 'Zveřejněním souhlasíte s <rules>pravidly a podmínkami</rules>.',
      },
      blocked: {
        title: 'Váš účet je zablokován.',
        reason: {
          repeated_violations:
            'Měli jste příliš mnoho příspěvků označených jako závadné. Příspěvky ani kategorie nelze přidávat a souznění vyjadřovat.',
          unknown: 'Příspěvky ani kategorie nelze přidávat a souznění vyjadřovat.',
        },
        help: 'Pokud si myslíte, že jde o omyl, <contact>napište nám</contact>. Podrobnosti najdete v <rules>pravidlech a podmínkách</rules>.',
      },
      moderation: {
        warn: {
          post: 'U příspěvku jsme našli možný problém. Zvažte jeho úpravu.',
          category: 'U kategorie jsme našli možný problém. Zvažte její úpravu.',
        },
        risk: {
          post: 'Příspěvek je potenciálně závadný nebo mimo téma. Při podrobnějším posouzení může být zablokován a smazán bez náhrady zaplacené částky.',
          category: 'Obsah je potenciálně závadný. Při podrobnějším posouzení může být kategorie zablokována.',
        },
        blocked: {
          post: 'Příspěvek nevyhovuje pravidlům nebo neodpovídá kategorii, a proto ho nelze zveřejnit.',
          category: 'Kategorie nevyhovuje pravidlům a zveřejnění není povoleno.',
        },
        violationScore: 'Porušení pravidel',
        topicScore: 'Neshoda s tématem kategorie',
        levelName: { ok: 'v pořádku', warn: 'doporučena úprava', risk: 'potenciální riziko', blocked: 'nepovoleno' },
        why: 'Proč:',
        foundIn: 'nalezeno',
        categoryIsAbout: 'kategorie je o (ve vašem textu chybí)',
        publishAnyway: 'Přesto zveřejnit',
        createAnyway: 'Přesto založit',
        edit: 'Upravit',
        seeRules: 'Co je dovoleno, určují <rules>pravidla a podmínky</rules>.',
        finding: {
          profanity: 'Obsahuje vulgární výrazy.',
          insult: 'Obsahuje urážky.',
          hate: 'Obsahuje nenávistné nebo diskriminační výrazy.',
          threat: 'Obsahuje výhrůžky nebo vyzývá k násilí.',
          spam_links: 'Obsahuje odkazy typické pro spam.',
          spam_phrases: 'Obsahuje fráze typické pro spam nebo podvody.',
          personal_data: 'Obsahuje osobní údaje (e-mail, telefon).',
          shouting: 'Je psán křikem (velká písmena, řetězce vykřičníků).',
          repetition: 'Opakuje stejná slova nebo znaky.',
          gibberish: 'Obsahuje nesrozumitelně dlouhé řetězce znaků.',
          spam: 'Vypadá jako spam nebo reklama.',
          sexual_content: 'Obsahuje nevhodný sexuální obsah.',
          self_harm: 'Vybízí k sebepoškozování.',
          illegal_content: 'Obsahuje nelegální obsah.',
          misinformation: 'Obsahuje záměrné dezinformace.',
          off_topic: 'Neodpovídá tématu kategorie.',
          ai_other: 'Další důvod byl nalezen při automatickém posouzení.',
          unknown: 'Další důvod byl nalezen při posouzení.',
        },
      },
      notification: {
        postBlocked: 'Váš příspěvek „{{title}}“ byl odstraněn pro porušení pravidel. Důvod: {{reason}}',
        accountBlocked:
          'Váš účet byl zablokován pro opakované porušení pravidel. Nelze přidávat příspěvky ani kategorie a vyjadřovat souznění.',
      },
      admin: {
        title: 'Moderace',
        loginRequired: 'Pro přístup k moderaci se přihlaste.',
        forbidden: 'K moderaci nemáte oprávnění.',
        error: 'Operace se nezdařila.',
        cancel: 'Zrušit',
        tabs: { posts: 'Příspěvky', rules: 'Pravidla kategorií', accounts: 'Zablokované účty' },
        status: { published: 'Zveřejněné', blocked: 'Zablokované', removed: 'Odstraněné', all: 'Všechny' },
        reason: {
          account_blocked: 'odstraněno se zablokováním účtu autora',
          repeated_violations: 'opakovaná porušení pravidel',
        },
        posts: {
          search: 'Hledat v textu',
          category: 'Kategorie (adresa)',
          status: 'Stav',
          minScore: 'Skóre od (%)',
          sort: 'Řazení',
          sortNew: 'Nejnovější',
          sortScore: 'Nejvyšší skóre',
          find: 'Najít',
          empty: 'Nic nenalezeno.',
          scores: 'porušení {{violation}} %, téma {{topic}} %',
          reason: 'Důvod blokace',
          author: 'Autor',
          authorBlocked: 'účet autora je zablokován',
          block: 'Zablokovat…',
          editRules: 'Pravidla kategorie',
          blocked: 'Příspěvek byl zablokován a autor upozorněn.',
          accountBlocked: 'Účet autora byl zablokován.',
          reasonLabel: 'Důvod (uvidí ho autor jako oznámení)',
          reasonHint: 'Příspěvek bude odstraněn bez náhrady zaplacené částky.',
          confirmBlock: 'Zablokovat příspěvek',
        },
        rules: {
          category: 'Kategorie (adresa)',
          load: 'Načíst',
          pick: 'Zadejte adresu kategorie.',
          source: 'Zdroj pravidel: {{source}}',
          none: 'žádná pravidla',
          sources: { algorithm: 'algoritmus', ai: 'model AI', admin: 'administrátor' },
          explain:
            'Příspěvky se porovnávají s těmito klíčovými slovy. Čím vyšší váha, tím víc slovo o kategorii vypovídá. Prázdný seznam vypne kontrolu tématu.',
          empty: 'Kategorie nemá žádná klíčová slova – kontrola tématu je vypnutá.',
          term: 'Klíčové slovo',
          weight: 'Váha',
          remove: 'Odebrat',
          add: '+ Přidat klíčové slovo',
          notes: 'Poznámky',
          save: 'Uložit pravidla',
          rebuild: 'Vytvořit znovu z názvu a popisu',
          confirmRebuild: 'Současná pravidla (včetně vašich úprav) se zahodí a vytvoří se znovu z názvu a popisu kategorie. Pokračovat?',
          saved: 'Pravidla byla uložena.',
          rebuilt: 'Pravidla byla vytvořena znovu.',
          invalid: 'Zkontrolujte pravidla – klíčová slova nesmí být prázdná a váha musí být mezi 0,1 a 10.',
        },
        accounts: {
          explain: 'Účty zablokované pro opakovaná porušení pravidel. Odblokováním účet začne s čistým štítem; odstraněné příspěvky se nevracejí.',
          empty: 'Žádné zablokované účty.',
          unblock: 'Odblokovat',
          confirmUnblock: 'Odblokovat účet? Dřívější porušení se přestanou počítat, odstraněné příspěvky se ale nevrátí.',
        },
      },
    },
    en: {
      nav: { categories: 'Categories' },
      common: { loading: 'Loading…', loadMore: 'Load more', retry: 'Try again' },
      list: {
        title: 'Categories',
        create: 'New category',
        loginToCreate: 'Sign in to create a category',
        moderation: 'Moderation',
        empty: 'There are no categories yet.',
        error: 'Could not load the categories.',
        posts_one: '{{count}} post',
        posts_other: '{{count}} posts',
      },
      category: {
        back: 'All categories',
        notFound: 'Category not found.',
        loadError: 'Could not load the category.',
        loginToPost: 'Sign in to add a post and to resonate.',
        empty: 'No posts here yet. Be the first.',
        error: 'Could not load the posts.',
      },
      post: {
        value: 'Value',
        resonances_one: '{{count}} resonance',
        resonances_other: '{{count}} resonances',
        resonate: 'Resonate',
        resonated: 'You resonated',
        loginToResonate: 'Sign in to resonate',
        resonateError: 'Could not save your resonance.',
      },
      form: {
        heading: 'Add a post',
        title: 'Title',
        body: 'Text',
        emoji: 'Emoji',
        counter: '{{current}} / {{max}}',
        publish: 'Publish',
        checking: 'Checking…',
        publishing: 'Publishing…',
        published: 'Your post was published. Posts are ordered by value, so it appears among the others accordingly.',
        invalid: 'Check the title and the text – they cannot be empty or too long.',
        error: 'Could not publish the post.',
        accountBlocked: 'Your account is blocked, so you cannot add posts.',
        rulesNotice: 'By publishing you agree to the <rules>terms and rules</rules>.',
      },
      newCategory: {
        title: 'New category',
        name: 'Name',
        nameHint: "The category's address is generated from its name.",
        description: 'Short description',
        descriptionHint: 'The name and description are turned into the rules that decide whether a post belongs in the category.',
        create: 'Create category',
        creating: 'Creating…',
        loginRequired: 'Sign in to create a category.',
        invalid: 'Check the name and the description – they cannot be empty or too long.',
        error: 'Could not create the category.',
        accountBlocked: 'Your account is blocked, so you cannot create categories.',
        rulesNotice: 'By publishing you agree to the <rules>terms and rules</rules>.',
      },
      blocked: {
        title: 'Your account is blocked.',
        reason: {
          repeated_violations:
            'Too many of your posts were marked as violating the rules. You cannot add posts or categories or resonate.',
          unknown: 'You cannot add posts or categories or resonate.',
        },
        help: 'If you think this is a mistake, <contact>write to us</contact>. You can read the details in the <rules>terms and rules</rules>.',
      },
      moderation: {
        warn: {
          post: 'We found a possible problem with your post. Consider editing it.',
          category: 'We found a possible problem with your category. Consider editing it.',
        },
        risk: {
          post: 'The post is potentially violating the rules or off-topic. After a closer review it may be blocked and deleted without a refund of what was paid for it.',
          category: 'The content is potentially violating. After a closer review the category may be blocked.',
        },
        blocked: {
          post: 'The post does not meet the rules or does not fit the category, so it cannot be published.',
          category: 'The category does not meet the rules and cannot be published.',
        },
        violationScore: 'Rule violation',
        topicScore: "Mismatch with the category's topic",
        levelName: { ok: 'fine', warn: 'edit recommended', risk: 'potential risk', blocked: 'not allowed' },
        why: 'Why:',
        foundIn: 'found',
        categoryIsAbout: 'the category is about (missing from your text)',
        publishAnyway: 'Publish anyway',
        createAnyway: 'Create anyway',
        edit: 'Edit',
        seeRules: 'What is allowed is set out in the <rules>terms and rules</rules>.',
        finding: {
          profanity: 'Contains vulgar expressions.',
          insult: 'Contains insults.',
          hate: 'Contains hateful or discriminatory expressions.',
          threat: 'Contains threats or incites violence.',
          spam_links: 'Contains links typical of spam.',
          spam_phrases: 'Contains phrases typical of spam or scams.',
          personal_data: 'Contains personal data (email, phone).',
          shouting: 'Is written in shouting (capitals, strings of exclamation marks).',
          repetition: 'Repeats the same words or characters.',
          gibberish: 'Contains unreadably long strings of characters.',
          spam: 'Looks like spam or advertising.',
          sexual_content: 'Contains inappropriate sexual content.',
          self_harm: 'Encourages self-harm.',
          illegal_content: 'Contains illegal content.',
          misinformation: 'Contains deliberate misinformation.',
          off_topic: 'Does not fit the category topic.',
          ai_other: 'Another reason was found by the automatic review.',
          unknown: 'Another reason was found in the review.',
        },
      },
      notification: {
        postBlocked: 'Your post "{{title}}" was removed for breaking the rules. Reason: {{reason}}',
        accountBlocked:
          'Your account was blocked for repeated rule violations. You can no longer add posts or categories or resonate.',
      },
      admin: {
        title: 'Moderation',
        loginRequired: 'Sign in to reach moderation.',
        forbidden: 'You are not allowed to moderate.',
        error: 'The operation failed.',
        cancel: 'Cancel',
        tabs: { posts: 'Posts', rules: 'Category rules', accounts: 'Blocked accounts' },
        status: { published: 'Published', blocked: 'Blocked', removed: 'Removed', all: 'All' },
        reason: {
          account_blocked: 'removed when its author was blocked',
          repeated_violations: 'repeated rule violations',
        },
        posts: {
          search: 'Search the text',
          category: 'Category (address)',
          status: 'State',
          minScore: 'Score from (%)',
          sort: 'Order',
          sortNew: 'Newest',
          sortScore: 'Highest score',
          find: 'Find',
          empty: 'Nothing found.',
          scores: 'violation {{violation}} %, topic {{topic}} %',
          reason: 'Reason for blocking',
          author: 'Author',
          authorBlocked: "the author's account is blocked",
          block: 'Block…',
          editRules: "Category's rules",
          blocked: 'The post was blocked and its author notified.',
          accountBlocked: "The author's account was blocked.",
          reasonLabel: 'Reason (the author will see it as a notification)',
          reasonHint: 'The post is removed without a refund of what was paid for it.',
          confirmBlock: 'Block the post',
        },
        rules: {
          category: 'Category (address)',
          load: 'Load',
          pick: "Enter a category's address.",
          source: 'Rules from: {{source}}',
          none: 'no rules',
          sources: { algorithm: 'the algorithm', ai: 'the AI model', admin: 'an administrator' },
          explain:
            "Posts are compared with these keywords. The higher the weight, the more the word says about the category. An empty list switches the topic check off.",
          empty: 'The category has no keywords - the topic check is off.',
          term: 'Keyword',
          weight: 'Weight',
          remove: 'Remove',
          add: '+ Add a keyword',
          notes: 'Notes',
          save: 'Save rules',
          rebuild: 'Rebuild from the title and description',
          confirmRebuild: "The current rules (your edits included) will be thrown away and built again from the category's title and description. Continue?",
          saved: 'The rules were saved.',
          rebuilt: 'The rules were rebuilt.',
          invalid: 'Check the rules - keywords cannot be empty and a weight must be between 0.1 and 10.',
        },
        accounts: {
          explain: 'Accounts blocked for repeated rule violations. Unblocking gives an account a clean slate; removed posts do not come back.',
          empty: 'No blocked accounts.',
          unblock: 'Unblock',
          confirmUnblock: 'Unblock this account? Earlier violations stop counting, but removed posts do not come back.',
        },
      },
    },
  },
}

export default boardsModule
