# Part of the With FBraun project template.
# Author: František Braun <frantisek.braun95@gmail.com>
# Freely available as a template for building custom applications.

"""add api documents and versions

Revision ID: 1ccb0c43f8db
Revises: abd019dc769f
Create Date: 2026-09-11 10:13:44.674948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ccb0c43f8db'
down_revision: Union[str, Sequence[str], None] = 'abd019dc769f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('recheck_period', sa.String(length=20), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_error', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_documents_team_id'), 'api_documents', ['team_id'], unique=False)
    op.create_table('api_document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('documentation_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('spec_title', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['documentation_id'], ['api_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_document_versions_documentation_id'), 'api_document_versions', ['documentation_id'], unique=False)
    op.create_index('uq_api_document_versions_current_per_doc', 'api_document_versions', ['documentation_id'], unique=True, postgresql_where=sa.text('archived_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_api_document_versions_current_per_doc', table_name='api_document_versions', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_index(op.f('ix_api_document_versions_documentation_id'), table_name='api_document_versions')
    op.drop_table('api_document_versions')
    op.drop_index(op.f('ix_api_documents_team_id'), table_name='api_documents')
    op.drop_table('api_documents')
    # ### end Alembic commands ###
