# Part of the With FBraun project template.
# Author: František Braun <frantisek.braun95@gmail.com>
# Freely available as a template for building custom applications.

"""add boards category moderation

Revision ID: 246e85165ed3
Revises: 6bf5abd01b44
Create Date: 2026-10-03 10:56:44.619461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246e85165ed3'
down_revision: Union[str, Sequence[str], None] = '6bf5abd01b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_boards_categories', sa.Column('status', sa.String(length=20), server_default='published', nullable=False))
    op.add_column('module_boards_categories', sa.Column('moderation_reason', sa.String(length=1000), nullable=True))
    op.add_column('module_boards_categories', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('module_boards_categories', sa.Column('moderated_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_module_boards_categories_status'), 'module_boards_categories', ['status'], unique=False)
    op.create_foreign_key('module_boards_categories_moderated_by_id_fkey', 'module_boards_categories', 'users', ['moderated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('module_boards_categories_moderated_by_id_fkey', 'module_boards_categories', type_='foreignkey')
    op.drop_index(op.f('ix_module_boards_categories_status'), table_name='module_boards_categories')
    op.drop_column('module_boards_categories', 'moderated_by_id')
    op.drop_column('module_boards_categories', 'moderated_at')
    op.drop_column('module_boards_categories', 'moderation_reason')
    op.drop_column('module_boards_categories', 'status')
    # ### end Alembic commands ###
