# Part of the With FBraun project template.
# Author: František Braun <frantisek.braun95@gmail.com>
# Freely available as a template for building custom applications.

"""add collections; extend subscriptions for collection targets

Revision ID: 2e229f19ace9
Revises: 910b717db521
Create Date: 2026-09-14 10:02:10.651108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e229f19ace9'
down_revision: Union[str, Sequence[str], None] = '910b717db521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_team_id'), 'collections', ['team_id'], unique=False)
    op.create_table('collection_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('documentation_id', sa.UUID(), nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['documentation_id'], ['api_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'documentation_id', name='uq_collection_documents_collection_id_documentation_id')
    )
    op.create_index(op.f('ix_collection_documents_collection_id'), 'collection_documents', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_documents_documentation_id'), 'collection_documents', ['documentation_id'], unique=False)
    # --- subscriptions: hand-edited from here down. Autogenerate correctly
    # picked up the new nullable collection_id column, the nullable relax on
    # documentation_id, and (this run) even the two partial unique indexes -
    # but it named the new FK constraint None (Postgres would auto-name it,
    # which downgrade() could then never resolve back to drop) and it always
    # misses CheckConstraints entirely, so both are fixed/added by hand below
    # per CLAUDE.md's migration hygiene note.
    op.add_column('subscriptions', sa.Column('collection_id', sa.UUID(), nullable=True))
    op.alter_column('subscriptions', 'documentation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_subscriptions_user_id_documentation_id'), 'subscriptions', type_='unique')
    op.create_index('uq_subscriptions_user_id_documentation_id', 'subscriptions', ['user_id', 'documentation_id'], unique=True, postgresql_where=sa.text('documentation_id IS NOT NULL'))
    op.create_index(op.f('ix_subscriptions_collection_id'), 'subscriptions', ['collection_id'], unique=False)
    op.create_index('uq_subscriptions_user_id_collection_id', 'subscriptions', ['user_id', 'collection_id'], unique=True, postgresql_where=sa.text('collection_id IS NOT NULL'))
    op.create_foreign_key('fk_subscriptions_collection_id_collections', 'subscriptions', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint(
        'ck_subscriptions_exactly_one_target',
        'subscriptions',
        '(documentation_id IS NOT NULL AND collection_id IS NULL) OR (documentation_id IS NULL AND collection_id IS NOT NULL)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # --- subscriptions: hand-edited (see upgrade() above). The CHECK
    # constraint and the FK on collection_id must both be dropped before
    # collection_id itself can be dropped as a column, so they come first,
    # in reverse of the order upgrade() added them.
    op.drop_constraint('ck_subscriptions_exactly_one_target', 'subscriptions', type_='check')
    op.drop_constraint('fk_subscriptions_collection_id_collections', 'subscriptions', type_='foreignkey')
    op.drop_index('uq_subscriptions_user_id_collection_id', table_name='subscriptions', postgresql_where=sa.text('collection_id IS NOT NULL'))
    op.drop_index(op.f('ix_subscriptions_collection_id'), table_name='subscriptions')
    op.drop_index('uq_subscriptions_user_id_documentation_id', table_name='subscriptions', postgresql_where=sa.text('documentation_id IS NOT NULL'))
    op.create_unique_constraint(op.f('uq_subscriptions_user_id_documentation_id'), 'subscriptions', ['user_id', 'documentation_id'])
    op.alter_column('subscriptions', 'documentation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('subscriptions', 'collection_id')
    op.drop_index(op.f('ix_collection_documents_documentation_id'), table_name='collection_documents')
    op.drop_index(op.f('ix_collection_documents_collection_id'), table_name='collection_documents')
    op.drop_table('collection_documents')
    op.drop_index(op.f('ix_collections_team_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
