# Part of the With FBraun project template.
# Author: František Braun <frantisek.braun95@gmail.com>
# Freely available as a template for building custom applications.

"""add stripe_payment_gate tables

Revision ID: 3eb07a820059
Revises: d10ac88ec00d
Create Date: 2026-09-27 20:08:41.166389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb07a820059'
down_revision: Union[str, Sequence[str], None] = 'd10ac88ec00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('return_path', sa.String(length=500), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    op.create_index(op.f('ix_stripe_payments_purpose'), 'stripe_payments', ['purpose'], unique=False)
    op.create_index(op.f('ix_stripe_payments_reference'), 'stripe_payments', ['reference'], unique=False)
    op.create_index(op.f('ix_stripe_payments_user_id'), 'stripe_payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_payments_user_id'), table_name='stripe_payments')
    op.drop_index(op.f('ix_stripe_payments_reference'), table_name='stripe_payments')
    op.drop_index(op.f('ix_stripe_payments_purpose'), table_name='stripe_payments')
    op.drop_table('stripe_payments')
    # ### end Alembic commands ###
