# Part of the With FBraun project template.
# Author: František Braun <frantisek.braun95@gmail.com>
# Freely available as a template for building custom applications.

"""add content_format to knowledge_base_pages

Revision ID: 425ac1f23494
Revises: be21ea1c7335
Create Date: 2026-09-21 14:04:25.883191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425ac1f23494'
down_revision: Union[str, Sequence[str], None] = 'be21ea1c7335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base_pages', sa.Column('content_format', sa.String(length=20), server_default='markdown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_base_pages', 'content_format')
    # ### end Alembic commands ###
