# Part of the With FBraun project template.
# Author: František Braun <frantisek.braun95@gmail.com>
# Freely available as a template for building custom applications.

"""add boards module tables

Revision ID: 433f37063a84
Revises: 4c65bdefdd5e
Create Date: 2026-10-02 11:37:13.759869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433f37063a84'
down_revision: Union[str, Sequence[str], None] = '4c65bdefdd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_boards_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_boards_categories_slug'), 'module_boards_categories', ['slug'], unique=True)
    op.create_table('module_boards_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=2048), nullable=False),
    sa.Column('paid_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('resonance_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('paid_cents >= 0', name='ck_module_boards_posts_paid_cents_nonneg'),
    sa.CheckConstraint('resonance_count >= 0', name='ck_module_boards_posts_resonance_count_nonneg'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['module_boards_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_boards_posts_author_id'), 'module_boards_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_module_boards_posts_category_id'), 'module_boards_posts', ['category_id'], unique=False)
    op.create_table('module_boards_resonances',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['module_boards_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_boards_resonances')
    op.drop_index(op.f('ix_module_boards_posts_category_id'), table_name='module_boards_posts')
    op.drop_index(op.f('ix_module_boards_posts_author_id'), table_name='module_boards_posts')
    op.drop_table('module_boards_posts')
    op.drop_index(op.f('ix_module_boards_categories_slug'), table_name='module_boards_categories')
    op.drop_table('module_boards_categories')
    # ### end Alembic commands ###
