# Part of the With FBraun project template.
# Author: František Braun <frantisek.braun95@gmail.com>
# Freely available as a template for building custom applications.

"""add knowledge base pages

Revision ID: 4b83b2c7bf66
Revises: 7655f4e21af7
Create Date: 2026-09-15 08:23:30.050816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b83b2c7bf66'
down_revision: Union[str, Sequence[str], None] = '7655f4e21af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('integration_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(collection_id IS NOT NULL AND integration_id IS NULL) OR (collection_id IS NULL AND integration_id IS NOT NULL)', name='ck_knowledge_base_pages_exactly_one_owner'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_pages_collection_id'), 'knowledge_base_pages', ['collection_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_pages_integration_id'), 'knowledge_base_pages', ['integration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_pages_integration_id'), table_name='knowledge_base_pages')
    op.drop_index(op.f('ix_knowledge_base_pages_collection_id'), table_name='knowledge_base_pages')
    op.drop_table('knowledge_base_pages')
    # ### end Alembic commands ###
