# Part of the With FBraun project template.
# Author: František Braun <frantisek.braun95@gmail.com>
# Freely available as a template for building custom applications.

"""add boards receipts

Revision ID: 6bf5abd01b44
Revises: 7a64a2325c95
Create Date: 2026-10-02 18:06:54.586993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf5abd01b44'
down_revision: Union[str, Sequence[str], None] = '7a64a2325c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_boards_receipt_counters',
    sa.Column('year', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('module_boards_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('email_to', sa.String(length=320), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('email_error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['stripe_payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_module_boards_receipts_user_id'), 'module_boards_receipts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_boards_receipts_user_id'), table_name='module_boards_receipts')
    op.drop_table('module_boards_receipts')
    op.drop_table('module_boards_receipt_counters')
    # ### end Alembic commands ###
