# Part of the With FBraun project template.
# Author: František Braun <frantisek.braun95@gmail.com>
# Freely available as a template for building custom applications.

"""add integrations

Revision ID: 7655f4e21af7
Revises: 2e229f19ace9
Create Date: 2026-09-14 11:03:03.720641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7655f4e21af7'
down_revision: Union[str, Sequence[str], None] = '2e229f19ace9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_team_id'), 'integrations', ['team_id'], unique=False)
    op.create_table('integration_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'collection_id', name='uq_integration_collections_integration_id_collection_id')
    )
    op.create_index(op.f('ix_integration_collections_collection_id'), 'integration_collections', ['collection_id'], unique=False)
    op.create_index(op.f('ix_integration_collections_integration_id'), 'integration_collections', ['integration_id'], unique=False)
    op.create_table('integration_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('documentation_id', sa.UUID(), nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['documentation_id'], ['api_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'documentation_id', name='uq_integration_documents_integration_id_documentation_id')
    )
    op.create_index(op.f('ix_integration_documents_documentation_id'), 'integration_documents', ['documentation_id'], unique=False)
    op.create_index(op.f('ix_integration_documents_integration_id'), 'integration_documents', ['integration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_documents_integration_id'), table_name='integration_documents')
    op.drop_index(op.f('ix_integration_documents_documentation_id'), table_name='integration_documents')
    op.drop_table('integration_documents')
    op.drop_index(op.f('ix_integration_collections_integration_id'), table_name='integration_collections')
    op.drop_index(op.f('ix_integration_collections_collection_id'), table_name='integration_collections')
    op.drop_table('integration_collections')
    op.drop_index(op.f('ix_integrations_team_id'), table_name='integrations')
    op.drop_table('integrations')
    # ### end Alembic commands ###
