# Part of the With FBraun project template.
# Author: František Braun <frantisek.braun95@gmail.com>
# Freely available as a template for building custom applications.

"""add boards moderation columns

Revision ID: 7a64a2325c95
Revises: 433f37063a84
Create Date: 2026-10-02 12:13:27.325937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a64a2325c95'
down_revision: Union[str, Sequence[str], None] = '433f37063a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_boards_categories', sa.Column('violation_score', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('module_boards_categories', sa.Column('machine_rules', sa.JSON(), nullable=True))
    op.add_column('module_boards_categories', sa.Column('machine_rules_source', sa.String(length=20), nullable=True))
    op.add_column('module_boards_categories', sa.Column('machine_rules_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('module_boards_posts', sa.Column('status', sa.String(length=20), server_default='published', nullable=False))
    op.add_column('module_boards_posts', sa.Column('violation_score', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('module_boards_posts', sa.Column('topic_mismatch_score', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('module_boards_posts', sa.Column('assessment', sa.JSON(), nullable=True))
    op.add_column('module_boards_posts', sa.Column('moderation_reason', sa.String(length=1000), nullable=True))
    op.add_column('module_boards_posts', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('module_boards_posts', sa.Column('moderated_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_module_boards_posts_status'), 'module_boards_posts', ['status'], unique=False)
    op.create_foreign_key('module_boards_posts_moderated_by_id_fkey', 'module_boards_posts', 'users', ['moderated_by_id'], ['id'])
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('blocked_reason', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('strikes_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'strikes_reset_at')
    op.drop_column('users', 'blocked_reason')
    op.drop_column('users', 'blocked_at')
    op.drop_column('users', 'is_blocked')
    op.drop_constraint('module_boards_posts_moderated_by_id_fkey', 'module_boards_posts', type_='foreignkey')
    op.drop_index(op.f('ix_module_boards_posts_status'), table_name='module_boards_posts')
    op.drop_column('module_boards_posts', 'moderated_by_id')
    op.drop_column('module_boards_posts', 'moderated_at')
    op.drop_column('module_boards_posts', 'moderation_reason')
    op.drop_column('module_boards_posts', 'assessment')
    op.drop_column('module_boards_posts', 'topic_mismatch_score')
    op.drop_column('module_boards_posts', 'violation_score')
    op.drop_column('module_boards_posts', 'status')
    op.drop_column('module_boards_categories', 'machine_rules_updated_at')
    op.drop_column('module_boards_categories', 'machine_rules_source')
    op.drop_column('module_boards_categories', 'machine_rules')
    op.drop_column('module_boards_categories', 'violation_score')
    # ### end Alembic commands ###
